//
// SPDX-License-Identifier: BSD-3-Clause
// Copyright Contributors to the OpenEXR Project.
//

#ifndef INCLUDED_IMATHCONFIG_H
#define INCLUDED_IMATHCONFIG_H

//
// This file is auto-generated by the configuration process for Imath
// This is a minimal configuration for Swift Package Manager builds
//

// Version information
#define IMATH_VERSION_STRING "3.1.12"
#define IMATH_PACKAGE_STRING "Imath 3.1.12"

#define IMATH_VERSION_MAJOR 3
#define IMATH_VERSION_MINOR 1
#define IMATH_VERSION_PATCH 12

#define IMATH_VERSION_HEX ((uint32_t(IMATH_VERSION_MAJOR) << 24) | \
                           (uint32_t(IMATH_VERSION_MINOR) << 16) | \
                           (uint32_t(IMATH_VERSION_PATCH) <<  8))

// Platform-specific configuration
#if defined(_WIN32) || defined(_WIN64)
    // Windows-specific settings
    #define IMATH_PLATFORM_WINDOWS
#elif defined(__APPLE__)
    // macOS/iOS/etc specific settings
    #define IMATH_PLATFORM_APPLE
#elif defined(__linux__)
    // Linux-specific settings
    #define IMATH_PLATFORM_LINUX
#endif

// Symbol visibility configuration
#if defined(__GNUC__) || defined(__clang__)
    #define IMATH_PUBLIC_SYMBOL_ATTRIBUTE __attribute__((visibility("default")))
    #define IMATH_PRIVATE_SYMBOL_ATTRIBUTE __attribute__((visibility("hidden")))
    #define IMATH_PUBLIC_TYPE_VISIBILITY_ATTRIBUTE __attribute__((type_visibility("default")))
#else
    #define IMATH_PUBLIC_SYMBOL_ATTRIBUTE
    #define IMATH_PRIVATE_SYMBOL_ATTRIBUTE
    #define IMATH_PUBLIC_TYPE_VISIBILITY_ATTRIBUTE
#endif

// Compiler optimization hints
#if defined(__GNUC__) || defined(__clang__)
    #define IMATH_LIKELY(x) __builtin_expect(!!(x), 1)
    #define IMATH_UNLIKELY(x) __builtin_expect(!!(x), 0)
#else
    #define IMATH_LIKELY(x) (x)
    #define IMATH_UNLIKELY(x) (x)
#endif

// noexcept configuration
#if __cplusplus >= 201103L
    #define IMATH_NOEXCEPT noexcept
#else
    #define IMATH_NOEXCEPT throw()
#endif

// constexpr14 configuration
#if __cplusplus >= 201402L
    #define IMATH_CONSTEXPR14 constexpr
#else
    #define IMATH_CONSTEXPR14
#endif

// Deprecation warnings
#if defined(__GNUC__) || defined(__clang__)
    #define IMATH_DEPRECATED(msg) __attribute__((deprecated(msg)))
#elif defined(_MSC_VER)
    #define IMATH_DEPRECATED(msg) __declspec(deprecated(msg))
#else
    #define IMATH_DEPRECATED(msg)
#endif

// Host/Device configuration (for CUDA support, but we don't use CUDA in SPM)
#define IMATH_HOSTDEVICE

// Namespace configuration
#define IMATH_INTERNAL_NAMESPACE Imath_3_1
#define IMATH_NAMESPACE Imath

#define IMATH_INTERNAL_NAMESPACE_HEADER_ENTER namespace IMATH_INTERNAL_NAMESPACE {
#define IMATH_INTERNAL_NAMESPACE_HEADER_EXIT }

#define IMATH_NAMESPACE_HEADER_ENTER \
    namespace IMATH_NAMESPACE { \
        using namespace IMATH_INTERNAL_NAMESPACE;

#define IMATH_NAMESPACE_HEADER_EXIT }

#endif // INCLUDED_IMATHCONFIG_H
